# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x18\n\nGetRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x1e\n\x0bGetResponse\x12\x0f\n\x07message\x18\x02 \x01(\t20\n\x04\x43hat\x12(\n\x0bSendMessage\x12\x0b.GetRequest\x1a\x0c.GetResponseB\x18Z\x16\x65xample.com/grpc/hellob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\026example.com/grpc/hello'
  _globals['_GETREQUEST']._serialized_start=17
  _globals['_GETREQUEST']._serialized_end=41
  _globals['_GETRESPONSE']._serialized_start=43
  _globals['_GETRESPONSE']._serialized_end=73
  _globals['_CHAT']._serialized_start=75
  _globals['_CHAT']._serialized_end=123
# @@protoc_insertion_point(module_scope)
