// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: go_service.proto

package go_servicepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Multiply_SendValues_FullMethodName = "/Multiply/SendValues"
)

// MultiplyClient is the client API for Multiply service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MultiplyClient interface {
	SendValues(ctx context.Context, in *RequestValues, opts ...grpc.CallOption) (*ResponseAnswer, error)
}

type multiplyClient struct {
	cc grpc.ClientConnInterface
}

func NewMultiplyClient(cc grpc.ClientConnInterface) MultiplyClient {
	return &multiplyClient{cc}
}

func (c *multiplyClient) SendValues(ctx context.Context, in *RequestValues, opts ...grpc.CallOption) (*ResponseAnswer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseAnswer)
	err := c.cc.Invoke(ctx, Multiply_SendValues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MultiplyServer is the server API for Multiply service.
// All implementations must embed UnimplementedMultiplyServer
// for forward compatibility.
type MultiplyServer interface {
	SendValues(context.Context, *RequestValues) (*ResponseAnswer, error)
	mustEmbedUnimplementedMultiplyServer()
}

// UnimplementedMultiplyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMultiplyServer struct{}

func (UnimplementedMultiplyServer) SendValues(context.Context, *RequestValues) (*ResponseAnswer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendValues not implemented")
}
func (UnimplementedMultiplyServer) mustEmbedUnimplementedMultiplyServer() {}
func (UnimplementedMultiplyServer) testEmbeddedByValue()                  {}

// UnsafeMultiplyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MultiplyServer will
// result in compilation errors.
type UnsafeMultiplyServer interface {
	mustEmbedUnimplementedMultiplyServer()
}

func RegisterMultiplyServer(s grpc.ServiceRegistrar, srv MultiplyServer) {
	// If the following call pancis, it indicates UnimplementedMultiplyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Multiply_ServiceDesc, srv)
}

func _Multiply_SendValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestValues)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiplyServer).SendValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Multiply_SendValues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiplyServer).SendValues(ctx, req.(*RequestValues))
	}
	return interceptor(ctx, in, info, handler)
}

// Multiply_ServiceDesc is the grpc.ServiceDesc for Multiply service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Multiply_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Multiply",
	HandlerType: (*MultiplyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendValues",
			Handler:    _Multiply_SendValues_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go_service.proto",
}
