// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: go_service.proto

package go_servicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value1        int32                  `protobuf:"varint,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2        int32                  `protobuf:"varint,2,opt,name=value2,proto3" json:"value2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestValues) Reset() {
	*x = RequestValues{}
	mi := &file_go_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestValues) ProtoMessage() {}

func (x *RequestValues) ProtoReflect() protoreflect.Message {
	mi := &file_go_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestValues.ProtoReflect.Descriptor instead.
func (*RequestValues) Descriptor() ([]byte, []int) {
	return file_go_service_proto_rawDescGZIP(), []int{0}
}

func (x *RequestValues) GetValue1() int32 {
	if x != nil {
		return x.Value1
	}
	return 0
}

func (x *RequestValues) GetValue2() int32 {
	if x != nil {
		return x.Value2
	}
	return 0
}

type ResponseAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ans           int32                  `protobuf:"varint,3,opt,name=ans,proto3" json:"ans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseAnswer) Reset() {
	*x = ResponseAnswer{}
	mi := &file_go_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAnswer) ProtoMessage() {}

func (x *ResponseAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_go_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAnswer.ProtoReflect.Descriptor instead.
func (*ResponseAnswer) Descriptor() ([]byte, []int) {
	return file_go_service_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseAnswer) GetAns() int32 {
	if x != nil {
		return x.Ans
	}
	return 0
}

var File_go_service_proto protoreflect.FileDescriptor

const file_go_service_proto_rawDesc = "" +
	"\n" +
	"\x10go_service.proto\"?\n" +
	"\rRequestValues\x12\x16\n" +
	"\x06value1\x18\x01 \x01(\x05R\x06value1\x12\x16\n" +
	"\x06value2\x18\x02 \x01(\x05R\x06value2\"\"\n" +
	"\x0eResponseAnswer\x12\x10\n" +
	"\x03ans\x18\x03 \x01(\x05R\x03ans2;\n" +
	"\bMultiply\x12/\n" +
	"\n" +
	"SendValues\x12\x0e.RequestValues\x1a\x0f.ResponseAnswer\"\x00B\x1fZ\x1dexample.com/grpc/go_servicepbb\x06proto3"

var (
	file_go_service_proto_rawDescOnce sync.Once
	file_go_service_proto_rawDescData []byte
)

func file_go_service_proto_rawDescGZIP() []byte {
	file_go_service_proto_rawDescOnce.Do(func() {
		file_go_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_go_service_proto_rawDesc), len(file_go_service_proto_rawDesc)))
	})
	return file_go_service_proto_rawDescData
}

var file_go_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_go_service_proto_goTypes = []any{
	(*RequestValues)(nil),  // 0: RequestValues
	(*ResponseAnswer)(nil), // 1: ResponseAnswer
}
var file_go_service_proto_depIdxs = []int32{
	0, // 0: Multiply.SendValues:input_type -> RequestValues
	1, // 1: Multiply.SendValues:output_type -> ResponseAnswer
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_go_service_proto_init() }
func file_go_service_proto_init() {
	if File_go_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_service_proto_rawDesc), len(file_go_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_go_service_proto_goTypes,
		DependencyIndexes: file_go_service_proto_depIdxs,
		MessageInfos:      file_go_service_proto_msgTypes,
	}.Build()
	File_go_service_proto = out.File
	file_go_service_proto_goTypes = nil
	file_go_service_proto_depIdxs = nil
}
