# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x04test\"*\n\tHiRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0f\n\x07request\x18\x02 \x01(\t\"\x1d\n\nHiResponse\x12\x0f\n\x07message\x18\x03 \x01(\t22\n\x04\x43hat\x12*\n\x05SayHi\x12\x0f.test.HiRequest\x1a\x10.test.HiResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HIREQUEST']._serialized_start=23
  _globals['_HIREQUEST']._serialized_end=65
  _globals['_HIRESPONSE']._serialized_start=67
  _globals['_HIRESPONSE']._serialized_end=96
  _globals['_CHAT']._serialized_start=98
  _globals['_CHAT']._serialized_end=148
# @@protoc_insertion_point(module_scope)
